### ISSUE TITLE
Parsing error on non-200 request when refresh=true

### ISSUE THREAD

**Issue by OJFord** [terraform-providers/terraform-provider-mailgun#10]
### Terraform Version
v0.10.8

### Affected Resource(s)
- mailgun_domain

### Terraform Configuration Files
```hcl
resource "mailgun_domain" "proxy" {
  name          = "${var.domain}"
  spam_action   = "disabled"
  smtp_password = "${var.smtp_password}"
}
```

### Expected Behavior
The resource exists and is unchanged; running with `refresh=false` correctly leaves it alone.

The error itself is odd and broken though - it shouldn't be 'destroying domain' on `plan`? And of course it shouldn't be getting a parsing error, unless the mailgun API really is responding with incomplete JSON!

### Actual Behavior
```sh
Error: Error refreshing state: 1 error(s) occurred:
* module.mailproxy.mailgun_domain.proxy: 1 error(s) occurred:
* module.mailproxy.mailgun_domain.proxy: mailgun_domain.proxy: Error retrieving domain: Error destroying domain: Error parsing error body for non-200 request: unexpected end of JSON input
```

### Steps to Reproduce
1. `terraform plan -refresh=true` (the default)

**Comment by brunoban** [comment]
The error message is not the best, but what probably is going on is that you probably didn't provide a api_key and/or smtp_password. At least adding that is what removed that message for me.

**Comment by wgebis** [comment]
Unable to reproduce, please look at the v0.2.0 (v3 Mailgun API client)
