### ISSUE TITLE
Add configuration to choose US or EU region for new domain

### ISSUE THREAD

**Issue by lupupitkanen** [terraform-providers/terraform-provider-mailgun#15]
### Feature request

Please add ability to choose in which Mailgun region (US or EU) the new domain should reside.

### Terraform Version
```
terraform -v
Terraform v0.11.7
+ provider.mailgun v0.1.0
```

### Affected Resource(s)
- mailgun_domain

### References
- https://documentation.mailgun.com/en/latest/api-intro.html#mailgun-regions
- US Endpoint: `api.mailgun.net`
- EU Endpoint: `api.eu.mailgun.net`

**Comment by wgebis** [comment]
Done in #24. `region` attribute is now supported in `domain` and `route` resource types.
