### ISSUE TITLE
 400 Bad Request: smtp_password cannot be set anymore

### ISSUE THREAD

**Issue by stillinbeta** [terraform-providers/terraform-provider-mailgun#16]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
$ terraform -v
Terraform v0.11.8
+ provider.google v1.17.1
+ provider.kubernetes v1.2.0
+ provider.local v1.1.0
+ provider.mailgun v0.1.0
+ provider.random v2.0.0
+ provider.template v1.0.0

terraform -v  1.80s user 0.15s system 103% cpu 1.887 total
```

### Affected Resource(s)
- mailgun_domain

### Terraform Configuration Files
```hcl
resource "random_string" "mailgun_password" {
  length = 64
  special = false
}

resource "mailgun_domain" "mg" {
  name = "${var.domain}"
  smtp_password = "${random_string.mailgun_password.result}"
}


resource "kubernetes_secret" "mailgun" {
  metadata = {
    namespace = "mastodon"
    name = "mailgun-secert"
  }

  data = {
    "SMTP_SERVER"=  "smtp.mailgun.org"
    "SMTP_PASSWORD" = "${mailgun_domain.mg.smtp_password}"
    "SMTP_LOGIN" = "${mailgun_domain.mg.smtp_login}"
  }
}

resource "google_dns_managed_zone" "mastodon" {
  name = "mastodon"
  dns_name = "${var.domain}"
}

resource "google_dns_record_set" "mailgun_send_records" {
  # seemingly does not work with resources
  # count = "${length(mailgun_domain.mg.sending_records)}"
  count = 2

  name = "${lookup(mailgun_domain.mg.sending_records[count.index], "name")}"
  type = "${lookup(mailgun_domain.mg.sending_records[count.index], "record_type")}"
  rrdatas = ["\"${lookup(mailgun_domain.mg.sending_records[count.index], "name")}\""]

  managed_zone = "${google_dns_managed_zone.mastodon.name}"
  ttl = 300
}

resource "google_dns_record_set" "mailgun_receive_records" {
  # seemingly does not work with resources
  # count = "${length(mailgun_domain.mg.receiving_records)}"
  count = 2

  name = "${lookup(mailgun_domain.mg.receiving_records[count.index], "name")}"
  type = "${lookup(mailgun_domain.mg.receiving_records[count.index], "record_type")}"
  rrdatas = ["\"${lookup(mailgun_domain.mg.receiving_records[count.index], "name")}\""]

  managed_zone = "${google_dns_managed_zone.mastodon.name}"
  ttl = 300
}
```

### Debug Output
I'll work on getting this, but seemingly every time I run the create method my mailgun domain gets locked and I need to file a support ticket to get it reopend.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
The domain should be created, then used to create the other certificates

### Actual Behavior
The record is created (as observed on the Mailgun website), but it errors out as well : `* mailgun_domain.mg: Error creating domain: API Error 400 Bad Request: smtp_password cannot be set anymore`. It's not marked as created 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out terraform.plan`
2. `terraform apply terraform.plan`

### Important Factoids
This is the free tier of Mailgun, if that helps.

**Comment by wgebis** [comment]
Done in #18 version v.0.2.0. Smtp password is retrieved as an attribute.
