### ISSUE TITLE
This provider is scheduled to be archived on September 27th, 2018.

### ISSUE THREAD

**Issue by randomcamel** [terraform-providers/terraform-provider-mailgun#17]
This Terraform provider is scheduled to be [archived](https://help.github.com/articles/archiving-repositories/) on September 27th, 2018. HashiCorp may archive providers when they have insufficient activity to maintain them at a level consistent with our open source guidelines and community expectations.

What does archiving mean?

1. The code repository and all commit, issue, and PR history will still be available.
1. Existing released binaries will remain available on the releases site and available to `terraform init`.
1. Documentation for the provider will remain on the Terraform website.
1. Issues and pull requests are not being monitored, merged, or added.
1. No new releases will be published.
1. Nightly acceptance tests may not be run.

If anyone from the community is willing to maintain this provider, please reach out to the [Terraform Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html) at **terraform-provider-dev@hashicorp.com**.

**Comment by phillbaker** [comment]
👋 hello @wgebis! It looks like you've restarted active development on this provider. As it's the original and has incorporated many of the request updates with https://github.com/terraform-providers/terraform-provider-mailgun/pull/18, it looks like there's no longer any major differences with the fork I was maintaining: https://github.com/phillbaker/terraform-provider-mailgunv3/. I'll go ahead and archive that fork, pointing folks here instead. How does that sound?

**Comment by wgebis** [comment]
Hello @phillbaker ! Nice to hear you 👋 ! Yep, sure, fell free to pointing guys to this official repo. My motivation for picking up the Mailgun plugin to the maintenance was the using the official golang Mailgun client. Some minor updated also have been committed. If you are still interested in the development and maintenance, just let me know.   
Thanks! 👍
