### ISSUE TITLE
Feature: Verification of a MailGun domain

### ISSUE THREAD

**Issue by dcmoeller** [terraform-providers/terraform-provider-mailgun#27]
Hi,

I would like to check whether verification of a MailGun `Domain` is still required or has already been achieved. And if not, of course, I would like to issue MailGun's verification procedure (after setting up all the required DNS resources your [`mailgun_domain` resource](https://www.terraform.io/docs/providers/mailgun/r/domain.html) already provides).

Therefore this feature request consists of two parts:

1. I suggest a Terraform Data element showing (at least) the `state` field of a [MailGun `Domain`](https://documentation.mailgun.com/en/latest/api-domains.html#domains). Or alternatively an appropriate `attribute` with your `mailgun_domain` resource.
2. A way to issue `Domain` verification with MailGun ... I'm not sure at the moment how to represent such an operation in Terraform appropriately.

Regards

Christian

**Comment by wgebis** [comment]
Done in v0.5.0 available in registry: https://registry.terraform.io/providers/wgebis/mailgun/latest.
