### ISSUE TITLE
Add Import Functionality to Mailgun Provider

### ISSUE THREAD

**Issue by zaksoup** [terraform-providers/terraform-provider-mailgun#3]
Hi there,

We use the Mailgun Provider to create Mailgun Domains for our app. We currently have a few domains and apps that we'd like to import into terraform, so I'm filing this issue. I'm reading through the docs and would like to submit this functionality as a PR myself, but any guidance you have would be appreciated.

### Terraform Version
N/A

### Affected Resource(s)
- mailgun_domain

**Comment by wgebis** [comment]
Done in #22
