### ISSUE TITLE
Adding SMTP_PASSWORD support is a breaking change

### ISSUE THREAD

**Issue by endzyme** [terraform-providers/terraform-provider-mailgun#33]
https://github.com/terraform-providers/terraform-provider-mailgun/blob/master/CHANGELOG.md#042-july-27-2020

We've recently upgraded your provider from v0.4.1 to v0.4.3 and found that the provider wants to recreate all our domains due to "force recreate" on `stmp_password` param. This really should have been a major version bump or at least a minor vs a patch.

No technical action needed, just some awareness on future releases as well as notes in the changelog. Thanks!

**Comment by wgebis** [comment]
Thanks for your feedback. Yep, there was no possibility to handle it without “force recreate” due to no domain modification endpoint on the Mailgun side, but I agree it should be better documented in changelog. 
I’m going to close the issue, let us know in case of any issues/ideas.
Cheers! 👍

**Comment by endzyme** [comment]
An idea might be to provide a migration plan for people to update their code without having to recreate resources. Usually in the form of a state removal and import, or (worst case scenario) manual state surgery.

**Comment by jbergknoff** [comment]
In my case, it was acceptable to ignore the changes:

```
lifecycle {
  ignore_changes = [
    smtp_password
  ]
}
```

Just throwing that out there for anybody else who comes across this.

**Comment by Chupaka** [comment]
Can't "smtp_password" be Computed or something, so that if it's not set explicitly, then current value from state is used?
