### ISSUE TITLE
Some of the important fields cannot be set

### ISSUE THREAD

**Issue by vojkny** [terraform-providers/terraform-provider-mailgun#35]
### Terraform Version
- `Terraform v0.12.29`
- `provider.mailgun v0.4.0`

### Affected Resource(s)
- `mailgun_domain`

### Terraform Configuration Files
```hcl
resource "mailgun_domain" "my_domain" {
  name          = "my_domain"
  region        = "us"
  smtp_login    = "postmaster@my.domain"
  smtp_password = "abcd"
  spam_action   = "disabled"
  wildcard      = false

  receiving_records = [
    {
      priority    = "10"
      record_type = "MX"
      valid       = "unknown"
      value       = "mxa.mailgun.org"
    },
  ]
  sending_records   = [
    {
      name        = "my.domain",
      record_type = "TXT"
      valid       = "valid"
      value       = "v=spf1 include:mailgun.org ~all"
    },
  ]
}
```

### Expected Behavior
When running `terraform plan` I would expect to get a change plan.

### Actual Behavior
```
Error: "receiving_records": this field cannot be set
  on main.tf line 32, in resource "mailgun_domain" "my_domain":

Error: "sending_records": this field cannot be set
  on main.tf line 32, in resource "mailgun_domain" "my_domain":

Error: "smtp_login": this field cannot be set
  on main.tf line 32, in resource "mailgun_domain" "my_domain":

Error: "smtp_password": this field cannot be set
  on main.tf line 32, in resource "mailgun_domain" "my_domain":
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
1. `terraform import mailgun_domain.my_domain XXX`
1. `terraform plan`

**Comment by vojkny** [comment]
@wgebis Hi, are you still part of this project?

**Comment by wgebis** [comment]
Hi @knyttl, yes, I saw the issue.

**Comment by wgebis** [comment]
would you upgrade plugin to v0.4.3 ?

**Comment by Chupaka** [comment]
@knyttl but you indeed cannot set those fields by design. They are generated by server, not set by you. They are attributes, not arguments.

**Comment by vojkny** [comment]
The upgrade helped, thanks!
