### ISSUE TITLE
Add resource type credential

### ISSUE THREAD

**Issue by sebglon** [terraform-providers/terraform-provider-mailgun#8]
### Affected Resource(s)
create new resource mailgun_credential

### Terraform Configuration Files
```hcl
resource "mailgun_domain" "my_domain" {
  name          = "mg.cloud.akeneo.com"
  spam_action   = "disabled"
  smtp_password = "${var.grafana_mailgun_pwd}"
}

resource "mailgun_credential" "mg_my_credential" {
  domain          = "${mailgun_domain.my_domain.name}"
  login              = "${var.maingul_login}"
  password      = "${var.mailgun_pwd}"
}
```
### Expected Behavior
Creating and importing credential on my terraform project

### Actual Behavior
Resource actually not implemented

**Comment by wgebis** [comment]
In v3 Mailgun API, credentials (smtp_password) could not be set upfront.
